const itemCost = 1000;
const totalDays = 30;
const amountInput = document.getElementById("quantityPerDay");

function check_quantity() {
    const amount = amountInput.value;
    if (amount < 0) {
        document.getElementById("errorValue").innerHTML = "Quantity cannot be negative.";
        amountInput.value = 0;
    } 
    else {
        document.getElementById("errorValue").innerHTML = "";
    }
}

function total_price() {
    const amount = amountInput.value;
    const finalTotal = itemCost * amount * totalDays;
    document.getElementById("totalPrice").value = finalTotal;

    if (finalTotal > 1000) {
        alert("Congratulations! You have earned a gift coupon.");
    }
    else {
        
    }
}
